export const TEXT_KEYS = [
  'hero.eyebrow', 'hero.lede', 'hero.stat1n', 'hero.stat1l',
  'hero.stat2n', 'hero.stat2l', 'hero.stat3n', 'hero.stat3l',
  'aud.1', 'aud.2', 'aud.3',
  'prog.1', 'prog.2', 'prog.3', 'prog.4',
  'coach.name', 'coach.title', 'coach.p1', 'coach.p2', 'coach.p3',
  'pb.lede',
  'ct.lede', 'ct.phone', 'ct.email', 'ct.ig', 'ct.area'
];

// tst.1/2/3 used to live here. The testimonials came off the site when the review
// placeholders were pulled for being unverified, and content.json lost the keys with
// them — but this list kept requiring all three. validateContentShape therefore
// returned three errors for the real content.json, and admin-content.mjs turns any
// error into a 422, so EVERY save from the admin panel was rejected. The panel loaded
// fine and only failed on Publish, which is why it went unnoticed.
// Put these back the same day real reviews go on the page, not before.

export const IMAGE_KEYS = [
  'hero.nets', 'rcp.trophy', 'rcp.team', 'rcp.juco', 'rcp.work', 'coach.portrait'
];

export const TEXT_GROUPS = {
  hero: ['hero.eyebrow', 'hero.lede', 'hero.stat1n', 'hero.stat1l', 'hero.stat2n', 'hero.stat2l', 'hero.stat3n', 'hero.stat3l'],
  audience: ['aud.1', 'aud.2', 'aud.3'],
  programs: ['prog.1', 'prog.2', 'prog.3', 'prog.4'],
  coach: ['coach.name', 'coach.title', 'coach.p1', 'coach.p2', 'coach.p3'],
  playbook: ['pb.lede'],
  contact: ['ct.lede', 'ct.phone', 'ct.email', 'ct.ig', 'ct.area']
};

export const TEXT_LABELS = {
  // Programs & pricing, fine print, enrollment steps (2026-09 restructure)
  'prog.2.th0': 'Price grid header: term',
  'prog.2.th1': 'Price grid header: once a week',
  'prog.2.th2': 'Price grid header: twice a week',
  'prog.2.r1': 'Price grid row 1 term',
  'prog.2.r1c1': '3 months, 1x/week price',
  'prog.2.r1c1s': '3 months, 1x/week detail',
  'prog.2.r1c2': '3 months, 2x/week price',
  'prog.2.r1c2s': '3 months, 2x/week detail',
  'prog.2.r2': 'Price grid row 2 term',
  'prog.2.r2c1': '12 months, 1x/week price',
  'prog.2.r2c1s': '12 months, 1x/week detail',
  'prog.2.r2c2': '12 months, 2x/week price',
  'prog.2.r2c2s': '12 months, 2x/week detail',
  'fp.eyebrow': 'Fine print eyebrow',
  'fp.1b': 'Fine print 1 label',
  'fp.1': 'Fine print 1',
  'fp.2b': 'Fine print 2 label',
  'fp.2': 'Fine print 2',
  'fp.3b': 'Fine print 3 label',
  'fp.3': 'Fine print 3',
  'fp.4b': 'Fine print 4 label',
  'fp.4': 'Fine print 4',
  'fp.5b': 'Fine print 5 label',
  'fp.5': 'Fine print 5',
  'fp.note1': 'Fine print note (before link)',
  'fp.link': 'Fine print terms link text',
  'fp.note2': 'Fine print note (after link)',
  'enr.eyebrow': 'Enroll eyebrow',
  'enr.h2': 'Enroll heading',
  'enr.lede': 'Enroll intro',
  'enr.1.title': 'Enroll step 1 title',
  'enr.1.body': 'Enroll step 1 body',
  'enr.2.title': 'Enroll step 2 title',
  'enr.2.body': 'Enroll step 2 body',
  'enr.3.title': 'Enroll step 3 title',
  'enr.3.body': 'Enroll step 3 body',
  'enr.4.title': 'Enroll step 4 title',
  'enr.4.body': 'Enroll step 4 body',
  'enr.bring.h': 'Session day heading',
  'enr.bring.p': 'Session day body',
  'enr.cta1': 'Enroll primary button',
  'enr.cta2': 'Enroll text-Coach button',
  'ct.row.phone': 'Contact phone row label',
  'ft.tagline': 'Footer tagline',
  'ft.col1h': 'Footer column 1 heading (Training)',
  'ft.col2h': 'Footer column 2 heading (Areas)',
  'ft.col3h': 'Footer column 3 heading (More)',
  'ft.bot': 'Footer bottom line',
  'ft.city': 'Footer city line',
  'ft.mob1': 'Mobile bar primary button',
  'ft.mob2': 'Mobile bar secondary button',
  'hero.eyebrow': 'Hero eyebrow line',
  'hero.lede': 'Hero opening paragraph',
  'hero.stat1n': 'Hero stat 1 number',
  'hero.stat1l': 'Hero stat 1 label',
  'hero.stat2n': 'Hero stat 2 number',
  'hero.stat2l': 'Hero stat 2 label',
  'hero.stat3n': 'Hero stat 3 number',
  'hero.stat3l': 'Hero stat 3 label',
  'aud.1': 'Middle school audience paragraph',
  'aud.2': 'High school audience paragraph',
  'aud.3': 'College track audience paragraph',
  'prog.1': 'First Look program description',
  'prog.2': 'Private training program description',
  'prog.3': 'Small group program description',
  'prog.4': 'College Track program description',
  'coach.name': 'Coach name',
  'coach.title': 'Coach title',
  'coach.p1': 'Coach bio paragraph 1',
  'coach.p2': 'Coach bio paragraph 2',
  'coach.p3': 'Coach bio paragraph 3',
  'pb.lede': 'Playbook section intro',
  'ct.lede': 'Contact section intro',
  'ct.phone': 'Phone number',
  'ct.email': 'Email address',
  'ct.ig': 'Instagram handle',
  'ct.area': 'Service area line',
  'area.eyebrow': "Service area eyebrow",
  'area.h2': "Service area heading",
  'area.lede': "Service area intro paragraph",
  'area.1.name': "Service area 1 name",
  'area.1.tier': "Service area 1 tier",
  'area.2.name': "Service area 2 name",
  'area.2.tier': "Service area 2 tier",
  'area.3.name': "Service area 3 name",
  'area.3.tier': "Service area 3 tier",
  'area.4.name': "Service area 4 name",
  'area.4.tier': "Service area 4 tier",
  'area.5.name': "Service area 5 name",
  'area.5.tier': "Service area 5 tier",
  'fam.eyebrow': "Families eyebrow",
  'fam.h2': "Families heading",
  'fam.lede': "Families intro paragraph",
  'fam.source': "Families source label",
  'fam.body': "Families body text",
  'faq.eyebrow': "FAQ eyebrow",
  'faq.h2': "FAQ heading",
  'faq.1.q': "FAQ 1 question",
  'faq.1.a': "FAQ 1 answer",
  'faq.2.q': "FAQ 2 question",
  'faq.2.a': "FAQ 2 answer",
  'faq.3.q': "FAQ 3 question",
  'faq.3.a': "FAQ 3 answer",
  'faq.4.q': "FAQ 4 question",
  'faq.4.a': "FAQ 4 answer",
  'faq.5.q': "FAQ 5 question",
  'faq.5.a': "FAQ 5 answer",
  'faq.6.q': "FAQ 6 question",
  'faq.6.a': "FAQ 6 answer",
  'coach.eyebrow': "Coach eyebrow",
  'coach.h2': "Coach heading",
  'coach.cred1.title': "Coach credential 1 title",
  'coach.cred1.sub': "Coach credential 1 subtitle",
  'coach.cred2.title': "Coach credential 2 title",
  'coach.cred2.sub': "Coach credential 2 subtitle",
  'coach.cred3.title': "Coach credential 3 title",
  'coach.cred3.sub': "Coach credential 3 subtitle",
  'coach.cred4.title': "Coach credential 4 title",
  'coach.cred4.sub': "Coach credential 4 subtitle",
  'sb.eyebrow': "Scoreboard eyebrow",
  'sb.h2': "Scoreboard heading",
  'sb.1.n': "Scoreboard stat 1 number",
  'sb.1.l': "Scoreboard stat 1 label",
  'sb.2.n': "Scoreboard stat 2 number",
  'sb.2.l': "Scoreboard stat 2 label",
  'sb.3.n': "Scoreboard stat 3 number",
  'sb.3.l': "Scoreboard stat 3 label",
  'sb.4.n': "Scoreboard stat 4 number",
  'sb.4.l': "Scoreboard stat 4 label",
  'sb.src': "Scoreboard source line",
  'ct.eyebrow': "Contact eyebrow",
  'ct.h2a': "Contact heading line 1",
  'ct.h2b': "Contact heading line 2",
  'ct.rev.source': "Contact reviews source label",
  'ct.rev.body': "Contact reviews body text",
  'ct.gatenote': "Contact form parent-gate note",
  'ct.lbl.name': "Contact field label name",
  'ct.lbl.phone': "Contact field label phone",
  'ct.lbl.email': "Contact field label email",
  'ct.lbl.area': "Contact field label area",
  'ct.lbl.msg': "Contact field label: message",
  'ct.consent': "Contact consent text",
  'ct.submit': "Contact submit button",
  'ct.trust': "Contact trust line",
  'ct.note1': "Contact note 1",
  'ct.note2': "Contact note 2",
  'ct.note3': "Contact note 3",
  'ct.done.h2': "Contact success panel heading",
  'ct.done.p1': "Contact success panel paragraph 1",
  'ct.done.p2a': "Contact success panel paragraph 2 lead-in",
  'ct.done.p2b': "Contact success panel paragraph 2 trailing",
  'ct.ph.name': "Contact placeholder name",
  'ct.ph.phone': "Contact placeholder phone",
  'ct.ph.email': "Contact placeholder email",
  'ct.ph.msg': "Contact placeholder: message",
  'mth.eyebrow': "Method eyebrow",
  'mth.h2': "Method heading",
  'mth.lede': "Method intro paragraph",
  'mth.1.title': "Method step 1 title",
  'mth.1.body': "Method step 1 body text",
  'mth.2.title': "Method step 2 title",
  'mth.2.body': "Method step 2 body text",
  'mth.3.title': "Method step 3 title",
  'mth.3.body': "Method step 3 body text",
  'mth.4.title': "Method step 4 title",
  'mth.4.body': "Method step 4 body text",
  'mth.5.title': "Method step 5 title",
  'mth.5.body': "Method step 5 body text",
  'nite.swish': "Night Court swish flash text",
  'nite.eyebrow': "Night Court eyebrow",
  'nite.h2': "Night Court heading",
  'nite.lede': "Night Court intro paragraph",
  'nite.trust': "Night Court trust line",
  'nite.cta': "Night Court CTA button",
  'nite.counter': "Night Court counter label",
  'pb.eyebrow': "Playbook eyebrow",
  'pb.h2': "Playbook heading",
  'pb.gatenote': "Playbook parent-gate note",
  'pb.lbl.name': "Playbook field label name",
  'pb.lbl.grade': "Playbook field label grade",
  'pb.lbl.email': "Playbook field label email",
  'pb.lbl.position': "Playbook field label position",
  'pb.lbl.focus': "Playbook field label focus",
  'pb.consent': "Playbook consent text",
  'pb.submit': "Playbook submit button",
  'pb.note1': "Playbook note 1",
  'pb.note2a': "Playbook note lead-in",
  'pb.note2b': "Playbook note middle",
  'pb.note2c': "Playbook note trailing punctuation",
  'pb.out.title': "Playbook output panel title",
  'pb.out.msg': "Playbook output panel message",
  'pb.sheet.head': "Playbook sample sheet heading",
  'pb.sheet.sub': "Playbook sample sheet subtitle",
  'pb.row1.label': "Playbook sample row 1 label",
  'pb.row1.text': "Playbook sample row 1 text",
  'pb.row2.label': "Playbook sample row 2 label",
  'pb.row2.text': "Playbook sample row 2 text",
  'pb.row3.label': "Playbook sample row 3 label",
  'pb.row3.text': "Playbook sample row 3 text",
  'pb.row4.label': "Playbook sample row 4 label",
  'pb.row4.text': "Playbook sample row 4 text",
  'pb.row5.label': "Playbook sample row 5 label",
  'pb.row5.text': "Playbook sample row 5 text",
  'pb.row6.label': "Playbook sample row 6 label",
  'pb.row6.text': "Playbook sample row 6 text",
  'pb.ph.name': "Playbook placeholder name",
  'pb.ph.email': "Playbook placeholder email",
  'prog.eyebrow': "Program eyebrow",
  'prog.h2': "Program heading",
  'prog.lede': "Program intro paragraph",
  'prog.1.tag': "Program 1 tag",
  'prog.1.title': "Program 1 title",
  'prog.1.price': "Program 1 price",
  'prog.1.unit': "Program 1 price unit",
  'prog.1.li1': "Program 1 list item 1",
  'prog.1.li2': "Program 1 list item 2",
  'prog.1.li3': "Program 1 list item 3",
  'prog.1.li4': "Program 1 list item 4",
  'prog.1.cta': "Program 1 CTA button",
  'prog.1.trust': "Program 1 trust line",
  'prog.2.tag': "Program 2 tag",
  'prog.2.title': "Program 2 title",
  'prog.2.price': "Program 2 price",
  'prog.2.unit': "Program 2 price unit",
  'prog.2.li1': "Program 2 list item 1",
  'prog.2.li2': "Program 2 list item 2",
  'prog.2.li3': "Program 2 list item 3",
  'prog.2.li4': "Program 2 list item 4",
  'prog.2.cta': "Program 2 CTA button",
  'prog.3.title': "Program 3 title",
  'prog.3.price': "Program 3 price",
  'prog.3.unit': "Program 3 price unit",
  'prog.3.li1': "Program 3 list item 1",
  'prog.3.li2': "Program 3 list item 2",
  'prog.3.li3': "Program 3 list item 3",
  'prog.3.li4': "Program 3 list item 4",
  'prog.3.cta': "Program 3 CTA button",
  'prog.4.title': "Program 4 title",
  'prog.4.price': "Program 4 price",
  'prog.4.unit': "Program 4 price unit",
  'prog.4.li1': "Program 4 list item 1",
  'prog.4.li2': "Program 4 list item 2",
  'prog.4.li3': "Program 4 list item 3",
  'prog.4.li4': "Program 4 list item 4",
  'prog.4.cta': "Program 4 CTA button",
  'rcp.eyebrow': "Résumé eyebrow",
  'rcp.h2': "Résumé heading",
  'rcp.lede': "Résumé intro paragraph",
  'rcp.1.year': "Résumé card 1 year",
  'rcp.1.title': "Résumé card 1 title",
  'rcp.1.body': "Résumé card 1 body text",
  'rcp.2.year': "Résumé card 2 year",
  'rcp.2.title': "Résumé card 2 title",
  'rcp.2.body': "Résumé card 2 body text",
  'rcp.3.year': "Résumé card 3 year",
  'rcp.3.title': "Résumé card 3 title",
  'rcp.3.body': "Résumé card 3 body text",
  'rcp.4.year': "Résumé card 4 year",
  'rcp.4.title': "Résumé card 4 title",
  'rcp.4.body': "Résumé card 4 body text",
  'rcp.note1': "Résumé note 1",
  'rcp.note2': "Résumé note 2",
  'rcp.note3': "Résumé note 3",
  'rcp.cta.b': "Résumé CTA note lead-in (bold)",
  'rcp.cta.rest': "Résumé CTA note remainder",
  'rcp.cta': "Résumé CTA button",
  'aud.eyebrow': "Audience eyebrow",
  'aud.h2': "Audience heading",
  'aud.lede': "Audience intro paragraph",
  'aud.1.badge': "Audience tile 1 badge",
  'aud.1.title': "Audience tile 1 title",
  'aud.2.badge': "Audience tile 2 badge",
  'aud.2.title': "Audience tile 2 title",
  'aud.3.badge': "Audience tile 3 badge",
  'aud.3.title': "Audience tile 3 title",
  'lkr.eyebrow': "Locker eyebrow",
  'lkr.h2': "Locker heading",
  'lkr.lede': "Locker intro paragraph",
  'lkr.1.meta': "Locker card 1 meta line",
  'lkr.1.badge': "Locker card 1 badge",
  'lkr.1.title': "Locker card 1 title",
  'lkr.1.body': "Locker card 1 body text",
  'lkr.1.cta': "Locker card 1 CTA button",
  'lkr.2.meta': "Locker card 2 meta line",
  'lkr.2.badge': "Locker card 2 badge",
  'lkr.2.title': "Locker card 2 title",
  'lkr.2.body': "Locker card 2 body text",
  'lkr.2.cta': "Locker card 2 CTA button",
  'lkr.3.meta': "Locker card 3 meta line",
  'lkr.3.badge': "Locker card 3 badge",
  'lkr.3.title': "Locker card 3 title",
  'lkr.3.body': "Locker card 3 body text",
  'lkr.3.cta': "Locker card 3 CTA button",
  'lkr.4.meta': "Locker card 4 meta line",
  'lkr.4.badge': "Locker card 4 badge",
  'lkr.4.title': "Locker card 4 title",
  'lkr.4.body': "Locker card 4 body text",
  'lkr.4.cta': "Locker card 4 CTA button",
  'lkr.5.meta': "Locker card 5 meta line",
  'lkr.5.badge': "Locker card 5 badge",
  'lkr.5.title': "Locker card 5 title",
  'lkr.5.body': "Locker card 5 body text",
  'lkr.5.cta': "Locker card 5 CTA button",
  'lkr.6.meta': "Locker card 6 meta line",
  'lkr.6.badge': "Locker card 6 badge",
  'lkr.6.title': "Locker card 6 title",
  'lkr.6.body': "Locker card 6 body text",
  'lkr.6.cta': "Locker card 6 CTA button",
  'lkr.note1': "Locker note 1",
  'lkr.notelink': "Locker note link text",
  'lkr.note2': "Locker note 2",
  'lkr.modal.eyebrow': "Locker login modal eyebrow",
  'lkr.modal.h3': "Locker login modal subheading",
  'lkr.modal.body': "Locker login modal body text",
  'lkr.modal.lbl': "Locker login modal email label",
  'lkr.modal.consent': "Locker login modal consent text",
  'lkr.modal.submit': "Locker login modal submit button",
  'lkr.modal.note1': "Locker login modal note 1",
  'lkr.modal.note2a': "Locker login modal note lead-in",
  'lkr.modal.note2b': "Locker login modal note middle",
  'lkr.modal.note2c': "Locker login modal note trailing punctuation",
  'lkr.sent.eyebrow': "Locker login-sent panel eyebrow",
  'lkr.sent.h3': "Locker login-sent panel subheading",
  'lkr.sent.body': "Locker login-sent panel body text",
  'lkr.in.eyebrow': "Locker logged-in panel eyebrow",
  'lkr.in.h3': "Locker logged-in panel subheading",
  'lkr.in.body1': "Locker logged-in panel body line 1",
  'lkr.in.body2': "Locker logged-in panel body line 2",
  'lkr.in.logout': "Locker logged-in panel log out button",
  'lkr.in.goto': "Locker logged-in panel go-to button",
  'lkr.modal.ph': "Locker login modal email placeholder",
  'nav.skiplink': "Nav skip link",
  'intro.sub': "Intro subtitle",
  'intro.skip': "Intro skip button",
  'nav.brand': "Nav brand name",
  'nav.link1': "Nav link 1",
  'nav.link2': "Nav link 2",
  'nav.link3': "Nav link 3",
  'nav.link4': "Nav link 4",
  'nav.link5': "Nav link 5",
  'nav.link6': "Nav link 6",
  'nav.link7': "Nav link 7",
  'nav.cta': "Nav CTA button",
  'hero.h1a': "Hero headline line 1",
  'hero.h1b': "Hero headline line 2",
  'hero.cta1': "Hero CTA button 1",
  'hero.cta2': "Hero CTA button 2",
  'hero.trust': "Hero trust line",
  'hero.cc.label': "Hero court card label",
  'hero.cc.date': "Hero court card date",
  'hero.cc.cap1': "Hero court card caption line 1",
  'hero.cc.cap2': "Hero court card caption line 2",
  'hero.cc.stat1n': "Hero court card stat 1 number",
  'hero.cc.stat1l': "Hero court card stat 1 label",
  'hero.cc.stat2n': "Hero court card stat 2 number",
  'hero.cc.stat2l': "Hero court card stat 2 label",
  'hero.cc.stat3n': "Hero court card stat 3 number",
  'hero.cc.stat3l': "Hero court card stat 3 label",
  'tick.1': "Ticker 1",
  'tick.2': "Ticker 2",
  'tick.3': "Ticker 3",
  'tick.4': "Ticker 4",
  'tick.5': "Ticker 5",
  'tick.6': "Ticker 6",
};

export const IMAGE_LABELS = {
  'hero.nets': 'Hero photo (net-cutting championship photo)',
  'rcp.trophy': 'Resume card 1 (Horizon League trophy)',
  'rcp.team': 'Resume card 2 (team celebration)',
  'rcp.juco': 'Resume card 3 (NJCAA Region 16)',
  'rcp.work': 'Resume card 4 (working with players)',
  'coach.portrait': 'Coach bio portrait'
};

export const IMAGE_ASPECT_RULES = {
  'hero.nets': { ratio: 0.74, tolerance: 0.18 },
  'rcp.trophy': { ratio: 0.8, tolerance: 0.15 },
  'rcp.team': { ratio: 0.8, tolerance: 0.15 },
  'rcp.juco': { ratio: 0.8, tolerance: 0.15 },
  'rcp.work': { ratio: 0.8, tolerance: 0.15 },
  'coach.portrait': { ratio: 0.8, tolerance: 0.15 }
};

export function validateContentShape(payload) {
  const errors = [];
  if (!payload || typeof payload !== 'object') return ['payload must be an object'];
  if (!payload.text || typeof payload.text !== 'object') errors.push('text object is required');
  if (!payload.images || typeof payload.images !== 'object') errors.push('images object is required');
  if (errors.length > 0) return errors;
  for (const key of TEXT_KEYS) {
    if (typeof payload.text[key] !== 'string' || payload.text[key].trim() === '') {
      errors.push('text field "' + key + '" is required and must be a non-empty string');
    }
  }
  for (const key of IMAGE_KEYS) {
    const image = payload.images[key];
    if (!image || typeof image !== 'object') {
      errors.push('image field "' + key + '" is required');
      continue;
    }
    if (!image.src || typeof image.src !== 'string') errors.push('image "' + key + '" is missing src');
    if (!image.alt || typeof image.alt !== 'string' || image.alt.trim() === '') errors.push('image "' + key + '" is missing required alt text');
  }
  return errors;
}
